[[main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

[[main]]
    identifier = "creative-writing"
    name = "Creative Writing"
    url = "/creative-writing"
    weight = 2

[[main]]
    identifier = "academic-writing"
    name = "Academic Writing"
    url = "/academic-writing"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "#"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "#"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "#"
    weight = 3